---
title: "Icthyoplankton"
author: "Ricky Tabandera"
date: "4/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("R.matlab")
library(R.matlab)
suppressPackageStartupMessages(library(tidyverse))
library(sf)
```


#### Density plot of survey stations
Ichyoplankton survey locations that captured black sea bass larva. Data sourced from `ECOMON` and `MARMAP` surveys. add metadata here


```{r cars}
# used to convert the .mat file into well behaved data frame

# 
# ich.data.raw<-readMat(here::here("Data","ichthyoplankton_all_species.mat"))
# ich.data<-data.frame(matrix(unlist(ich.data.raw), nrow=length(ich.data.raw$taxa), ncol = (length(ich.data.raw))))
# ich.names<-c("taxa" ,"year", "season", "strata" ,"lat", "lon" ,"area" ,"mean.abund","rel.proportion")
# colnames(ich.data)<-ich.names
# ich.data <- ich.data %>%   mutate_at(vars(-taxa) ,as.numeric)
# Save the data to a useful format

# saveRDS(ich.data, file="ichthyoplankton_MARMAP_ECOMON.rds")



ich.data<-read_rds(here::here("data","ichthyoplankton_MARMAP_ECOMON.rds"))

selected_spp<-ich.data %>% filter(taxa =="Centropristis_striata")

  selected_spp <- selected_spp %>%
    dplyr::mutate(decade = ggplot2::cut_width(year, width = 10, center = 1980))


geo_lim<-selected_spp %>% summarise(latmin= min(lat, na.rm = TRUE )-1,
                                   latmax= max(lat, na.rm = TRUE)+1,
                                   lonmin= min(lon, na.rm = TRUE)-1,
                                   lonmax= max(lon, na.rm = TRUE)+1)


ggplot(data= ecodata::coast )+
  
  # geom_point(data = selected_spp, aes(x = lon,y = lat, color = as.numeric(year)))+ 
   ggplot2::stat_density2d(aes( x = lon, 
                                y = lat, 
                               fill = ..density..),
                               geom = "raster",
                               contour=FALSE,
                               alpha = 0.9, data = selected_spp)+
   geom_sf()+
  ggplot2::coord_sf(xlim = c(geo_lim$lonmin+1.2 , geo_lim$lonmax-1.2), 
                      ylim = c(geo_lim$latmin+1.2 , geo_lim$latmax-1.2 )) +
  scale_color_gradient(low = "blue", 
                         high = "red", 
                         name = "Year") +
 
  xlab("Longitude") +
  ylab("Latitude")

  
  




```

## Including Plots

You can also embed plots, for example:

```{r Relative_proportion plot, fig.cap = paste("Black sea bass", "larva relative proportion")}

if(nrow(selected_spp)>5){
selected_spp.1<-filter_all(selected_spp, ~!is.na(.))

selected_spp.1 <- selected_spp.1 %>%
    dplyr::mutate(rel.prop.bin = ggplot2::cut_interval(rel.proportion, length = 25))


geo_lim.1<-selected_spp.1 %>% summarise(latmin= min(lat, na.rm = TRUE )-1,
                                   latmax= max(lat, na.rm = TRUE)+1,
                                   lonmin= min(lon, na.rm = TRUE)-1,
                                   lonmax= max(lon, na.rm = TRUE)+1)






 ggplot()+
   geom_sf()+
   ggplot2::coord_sf(xlim = c(geo_lim$lonmin - 1, geo_lim$lonmax + 1), 
                      ylim = c(geo_lim$latmin - 1, geo_lim$latmax + 1)) +
   geom_point(data =  selected_spp.1 ,aes(x=lon,y=lat,  size=(mean.abund),color=rel.prop.bin))+
   facet_wrap(~(decade))+
   nmfspalette::scale_color_nmfs("seagrass")+
      geom_sf(data = ecodata::coast)+
   ggplot2::coord_sf(xlim = c(geo_lim.1$lonmin + 1, geo_lim.1$lonmax - 1), 
                      ylim = c(geo_lim.1$latmin + 1, geo_lim.1$latmax - 1))+
   labs( size="Mean abundance", color="Relative proportion (%)")+
   xlab("Longitude")+
   ylab("Latitude")
}else("No data")

   
   


```

