# Summary of statistically significant indicators

```{r, output_summary}
source(here::here("R/full_report_functions", "make_html_table.R"))

summary_table <- function(x){
    DT::datatable(x,
                  rownames = FALSE,
                  filter = list(position = 'top', 
                                clear = FALSE),
                  options = list(search = list(regex = TRUE),
                                 paging = FALSE))
}

colnames(output) <- c("Response_variable", "Indicator", 
                                 "Number of data points", "Slope", 
                                 "P-value", "R2_adj")
```

## Abundance
```{r, eval = TRUE}
output %>% 
  tibble::as_tibble() %>%
  dplyr::filter(Response_variable == "Abundance",
                R2_adj < 1) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()


```

## Recruitment
```{r, eval = TRUE}
output %>% 
  tibble::as_tibble() %>%
  dplyr::filter(Response_variable == "Recruitment",
                R2_adj != 1) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()

```

## Catch
```{r, eval = TRUE}
output %>% 
  tibble::as_tibble() %>%
  dplyr::filter(Response_variable == "Catch",
                R2_adj != 1) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()

```

## Fmort
```{r, eval = TRUE}
output %>% 
  tibble::as_tibble() %>%
  dplyr::filter(Response_variable == "Fmort",
                R2_adj != 1) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()

```

