name: 'Create reports'
description: 'Render ESP reports'
inputs:
  species:  #  species indices
    description: 'Which all_species to include (numeric)'
    required: true
    default: '1'

runs:
   using: "composite"
   steps:
      - run: |
          nums <- ${{ inputs.species }}
          source(here::here("bookdown/render", "render_bookdown_ghaction.R"))
        shell: Rscript {0}
