## Distribution

```{r, geo_functions, cache = params$cache}
source(here::here("R/full_report_functions", "get_latlong.R"))
source(here::here("R/full_report_functions", "map_strata_ecsa.R"))
```

```{r, geo_data_species}
latlong_data <- params$latlong_data[params$latlong_data$Species == species, ]
```

### Map of distribution
Strata maps were pulled and compiled using code from [NOAA/EDAB ECSA](https://github.com/NOAA-EDAB/ECSA). Please note, only fall and spring strata are shown on the map.
```{r, ecsa_map}
map_strata_ecsa(data = latlong_data,
                species_name = species)
```

### Latitude and longitude ranges
Latitude and longitude ranges were calculated from NOAA/EDAB ECSA [seasonal species strata](https://github.com/NOAA-EDAB/ECSA/blob/master/data/seasonal_stock_strata.csv) and [Bottom Trawl Survey (BTS) shapefiles](https://github.com/NOAA-EDAB/ECSA/tree/master/data/strata_shapefiles). The coordinate system is WGS84.
```{r, latlong}
data <- get_latlong(species, latlong_data, shapefile = params$shape) %>%
  character_to_factor()

make_html_table(data, col_names = colnames(data))
```
