## Recruitment

```{r, child = system.file("indicator_bookdown_template/_legend-child-doc.Rmd", package = "NEesp")}
```

Recruitment data were pulled from ``r params$asmt_source``. Separate geom_gls() functions were fit for each region; trend lines are only shown when the trend was statistically significant, so some plots may have fewer trend lines than regions.

### Figure
```{r}
if (nrow(asmt_data %>% dplyr::filter(Metric == "Recruitment")) > 0) {
  ndesc <- asmt_data %>%
    dplyr::filter(Metric == "Recruitment") %>%
    # dplyr::mutate(options = paste(Description, Units)) %>%
    dplyr::select(Age) %>%
    unique() %>%
    nrow()
} else {
  ndesc <- 1
}
```

```{r, recruitment, fig.height = ndesc * 4 + 1}
NEesp::plot_asmt(asmt_data,
  metric = "Recruitment",
  ytitle = "Recruitment",
  lin = lines,
  col = colors
)
```

##### Risk {-}

See Methods for risk calculation details.
```{r}
indicators <- c("recruitment")
```

```{r, child = system.file("indicator_bookdown_template/_risk-child-doc.Rmd", package = "NEesp")}
```

### Data

```{r, recruit_data}
data <- asmt_data %>%
  dplyr::filter(Metric == "Recruitment") %>%
  dplyr::select(-Species, -Metric) %>%
  dplyr::mutate(Value = Value %>%
    round(digits = 0)) %>%
  dplyr::mutate(Value = Value %>%
    format(
      big.mark = ",",
      scientific = FALSE
    )) %>%
  NEesp::character_to_factor()

NEesp::make_html_table(data, col_names = colnames(data))
```
