## F/Fmsy 

```{r, f_status}
if (length(asmt_sum_data$Species) > 1) {
  list_regions <- split(unique(asmt_sum_data$Region),
    f = list(unique(asmt_sum_data$Region))
  )
  ffmsy2 <- purrr::map(
    list_regions,
    ~ NEesp::status(
      data = asmt_sum_data,
      regions = .x,
      metric = "ffmsy"
    )
  )
} else {
  ffmsy2 <- "UNKNOWN"
}
```

```{r, child = system.file("indicator_bookdown_template/_legend-child-doc.Rmd", package = "NEesp")}
```

F/Fmsy data were pulled from ``r params$asmt_sum_source``.

The most recent status of F/Fmsy is: `r ffmsy2`

### Figure


```{r, ffmsy, fig.cap = paste(species, "F/Fmsy")}
if ("GOOD" %in% ffmsy2 | "DANGER" %in% ffmsy2) {
  NEesp::plot_msy(asmt_sum_data[which(is.na(asmt_sum_data$`F/Fmsy`) == FALSE), ],
    ytitle = "F / Fmsy",
    type = "f",
    lin = lines,
    col = colors
  )
} else {
  print("NO DATA")
}
```


##### Risk {-}

See Methods for risk calculation details.
```{r}
indicators <- c("ffmsy")
```

```{r, child = system.file("indicator_bookdown_template/_risk-child-doc.Rmd", package = "NEesp")}
```

### Data
```{r, ffmsy_data}
data <- asmt_sum_data[which(is.na(asmt_sum_data$`F/Fmsy`) == FALSE), ] %>%
  dplyr::select(Region, `Assessment Year`, `F/Fmsy`) %>%
  dplyr::mutate(`F/Fmsy` = `F/Fmsy` %>% round(digits = 2)) %>%
  NEesp::character_to_factor()

NEesp::make_html_table(data, col_names = c("Region", "Year", "F/Fmsy"))
```
