# Summary of statistically significant indicators

```{r, output_summary}
summary_table <- function(x) {
  DT::datatable(x,
    rownames = FALSE,
    filter = list(
      position = "top",
      clear = FALSE
    ),
    options = list(
      search = list(regex = TRUE),
      paging = FALSE
    )
  )
}

colnames(output) <- c(
  "Response_variable", "Indicator",
  "Number of data points", "Slope",
  "P-value", "R2_adj"
)
```

## Abundance
```{r}
output %>%
  tibble::as_tibble() %>%
  dplyr::filter(
    Response_variable == "Abundance",
    R2_adj < 1
  ) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()
```

### Generalized linear model

```{r, bonf}
# bonferroni correction to weed out excess covariates
bonf_p <- 0.05/length(unique(abun_data$Var))
```

```{r, wrangle-abun}
abun_data <- abun_data %>%
  dplyr::mutate(Var = Var %>%
  stringr::str_replace_all(" ", "_") %>%
  stringr::str_replace_all("-", "_") %>%
  stringr::str_replace_all("/", "_") %>%
  stringr::str_replace_all("[:^:]", "_") %>%
  stringr::str_replace("\n", "_")
  ) %>%
  dplyr::filter(pval < bonf_p,
                Var != "Time") %>%
  dplyr::select(-pval)

abun_data <- abun_data %>%
  tidyr::pivot_wider(names_from = Var,
                     values_from = Val) %>%
  tidyr::drop_na()

start_model <- glm(Value ~ 1,
                   data = abun_data,
                   family = poisson())

full_mod <- paste(colnames(abun_data)[6:ncol(abun_data)],
                  collapse = " + ")
full_mod <- paste("~", full_mod)

```

```{r, new-model-abun}
new_mod <- MASS::stepAIC(start_model,
              k = log(nrow(abun_data)),
              trace = FALSE,
              scope = list(lower = ~1,
                           upper = full_mod))

summary(new_mod)$coefficients %>% knitr::kable()
```


```{r, predict-abun}
abun_data$Predicted <- predict(new_mod, newdata = abun_data) %>% exp()

fig <- ggplot2::ggplot(abun_data,
       ggplot2::aes(x = Time,
           y = Value))+
  ggplot2::geom_line()+
  ggplot2::geom_point()+
  ggplot2::geom_line(ggplot2::aes(y = Predicted),
            lty = 2,
            color = "red")+
  ggplot2::geom_point(ggplot2::aes(y = Predicted),
               color = "red")+
  ggplot2::ylab("Abundance")+
  ggplot2::xlab("Year")+
  ggplot2::theme_bw()+
  ggplot2::scale_y_continuous(labels = scales::comma,
                     limits = c(0, NA))

print(fig)
```


## Recruitment
```{r}
output %>%
  tibble::as_tibble() %>%
  dplyr::filter(
    Response_variable == "Recruitment",
    R2_adj != 1
  ) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()
```

### Generalized linear model
```{r, bonf-recruit}
# bonferroni correction to weed out excess covariates
bonf_p <- 0.05/length(unique(recruit_data$Var))
```

```{r, wrangle-recruit}
recruit_data <- recruit_data %>%
  dplyr::mutate(Var = Var %>%
  stringr::str_replace_all(" ", "_") %>%
  stringr::str_replace_all("-", "_") %>%
  stringr::str_replace_all("/", "_") %>%
  stringr::str_replace_all("[:^:]", "_") %>%
  stringr::str_replace("\n", "_")
  ) %>%
  dplyr::filter(pval < bonf_p,
                Var != "Time") %>%
  dplyr::select(-pval)

recruit_data <- recruit_data %>%
  tidyr::pivot_wider(names_from = Var,
                     values_from = Val) %>%
  tidyr::drop_na() 

start_model <- glm(Value ~ 1,
                   data = recruit_data,
                   family = poisson())

full_mod <- paste(colnames(recruit_data)[6:ncol(recruit_data)],
                  collapse = " + ")
full_mod <- paste("~", full_mod)

```

```{r, new-model-recruit}
new_mod <- MASS::stepAIC(start_model,
              k = log(nrow(recruit_data)),
              trace = FALSE,
              scope = list(lower = ~1,
                           upper = full_mod))

summary(new_mod)$coefficients %>% knitr::kable()
```


```{r, predict-recruit}
recruit_data$Predicted <- predict(new_mod, newdata = recruit_data) %>% exp()

fig <- ggplot2::ggplot(recruit_data,
       ggplot2::aes(x = Time,
           y = Value))+
  ggplot2::geom_line()+
  ggplot2::geom_point()+
  ggplot2::geom_line(ggplot2::aes(y = Predicted),
            lty = 2,
            color = "red")+
  ggplot2::geom_point(ggplot2::aes(y = Predicted),
               color = "red")+
  ggplot2::ylab("Abundance")+
  ggplot2::xlab("Year")+
  ggplot2::theme_bw()+
  ggplot2::scale_y_continuous(labels = scales::comma,
                     limits = c(0, NA))

print(fig)
```


## Catch
```{r}
output %>%
  tibble::as_tibble() %>%
  dplyr::filter(
    Response_variable == "Catch",
    R2_adj != 1
  ) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()
```

## Fmort
```{r}
output %>%
  tibble::as_tibble() %>%
  dplyr::filter(
    Response_variable == "Fmort",
    R2_adj != 1
  ) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()
```

