```{r}
if ("EPU" %in% colnames(test)) {
  eval_epu <- sum(test$EPU %in% params$epu) > 0 # only evaluate if the selected epu is in the indicator data set
} else {
  eval_epu <- TRUE
} # always evaluate if there is no epu for the indicator
```

````{r, eval = eval_epu}
# make sure test data has the right structure
if ("EPU" %in% colnames(test)) {
  test <- test %>%
    dplyr::filter(EPU %in% params$epu)
}

if ("Units" %in% colnames(test)) {
  test <- test %>%
    dplyr::mutate(Var = paste(Var, Units, sep = "\n"))
}

if ("Value" %in% colnames(test)) {
  test <- test %>%
    dplyr::rename(Val = Value)
}

# mean data by year
test <- test %>%
  dplyr::ungroup() %>%
  dplyr::group_by(Var, Time) %>%
  dplyr::summarise(new_val = mean(Val)) %>%
  dplyr::rename(Val = new_val) %>%
  dplyr::ungroup()

n_years <- length(unique(test$Time))
n_var <- length(unique(test$Var))
n_measurements <- length(test$Time)

if (n_measurements > n_years * n_var &
  n_measurements > 0) {
  test <- test %>%
    dplyr::mutate(Var = paste(Var, "(annual mean)", sep = "\n"))
}

# correlation summary
output <- rbind(output, NEesp::correlation_summary(
  stock = stock,
  eco = test,
  lag = params$lag
))

# make name for figure
knitr::opts_knit$set(unnamed.chunk.label = names[1])
```

```{r, eval = params$save & eval_epu}
data <- NEesp::data_prep(
  stock = stock,
  eco = test,
  lag = params$lag
)

if (nrow(data) > 0) {
  file_name <- paste(params$stock, params$region, params$epu[1],
    params$lag, "lag",
    params$remove_recent, "remove_recent", names[1],
    ".csv",
    sep = "_"
  ) %>%
    stringr::str_replace_all("/", "-") %>%
    stringr::str_replace_all("Georges Bank", "GB") %>%
    stringr::str_replace_all("Gulf of Maine", "GOM") %>%
    stringr::str_replace_all("Northern", "N") %>%
    stringr::str_replace_all("Southern", "S") %>%
    stringr::str_replace_all("Northwestern", "NW") %>%
    stringr::str_replace_all(" - ", "-") %>%
    stringr::str_replace_all("_.csv", ".csv") %>%
    stringr::str_replace_all(" ", "_")

  write.csv(data, paste("data/", file_name, sep = ""))

  # prep for fig
  # remove na's,
  # count number of regressions for bonferroni correction
  data <- data %>%
    tidyr::drop_na()
  var_names <- unique(test$Var)
  nvar <- length(var_names)
  bonf_n <- bonf_n + nvar
}
```

#### Figures {-}
```{r, {{label}}-fig, eval = eval_epu, fig.height = 10}
if (nvar > 6) { # break up into multiple graphs
  for (i in 1:round(nvar / 6)) {
    index <- ((i - 1) * 6 + 1):(i * 6)
    dat <- data %>%
      dplyr::filter(Var %in% var_names[index])

    fig <- try(NEesp::plot_correlation(
      data = dat,
      lag = params$lag
    ))

    if (class(fig) == "try-error") {
      print(fig)
    }

    cat("\n\n")
  }
} else {
  NEesp::plot_correlation(
    data = data,
    lag = params$lag
  )
}
```

```{r, eval = (eval_epu == FALSE)}
print("No data for the EPU selected")
```

#### Regression statistics {-}
```{r, results = "asis", eval = eval_epu}
NEesp::correlation_data(
  stock = stock,
  eco = test,
  lag = params$lag
)
```

```{r, eval = (eval_epu == FALSE)}
print("No data for the EPU selected")
```

```{r, eval = eval_epu}
#### Regression data
this_recruit <- data %>%
  dplyr::filter(
    Metric == "Recruitment",
    sig == TRUE
  ) %>%
  dplyr::select(Species, Region, Time, Value, Metric, Var, Val, pval)

if (nrow(this_recruit) > 0) {
  recruit_data <- rbind(recruit_data, this_recruit)
}

this_abun <- data %>%
  dplyr::filter(
    Metric == "Abundance",
    sig == TRUE
  ) %>%
  dplyr::select(Species, Region, Time, Value, Metric, Var, Val, pval)

if (nrow(this_abun) > 0) {
  abun_data <- rbind(abun_data, this_abun)
}
```

```{r}
names <- names[-1]
```
