```{r}
data <- data %>%
  tidyr::pivot_wider(
    names_from = Var,
    values_from = Val
  ) %>%
  tidyr::drop_na()

file_name <- paste(params$stock, params$region, params$epu[1],
  params$lag, "lag",
  params$remove_recent, "remove_recent", type, "model_data",
  ".csv",
  sep = "_"
) %>%
  stringr::str_replace_all("/", "-") %>%
  stringr::str_replace_all("Georges Bank", "GB") %>%
  stringr::str_replace_all("Gulf of Maine", "GOM") %>%
  stringr::str_replace_all("Northern", "N") %>%
  stringr::str_replace_all("Southern", "S") %>%
  stringr::str_replace_all("Northwestern", "NW") %>%
  stringr::str_replace_all(" - ", "-") %>%
  stringr::str_replace_all("_.csv", ".csv") %>%
  stringr::str_replace_all(" ", "_")

write.csv(data, paste("data/", file_name, sep = ""))

start_model <- glm(Value ~ 1,
  data = data,
  family = poisson()
)

full_mod <- paste(colnames(data)[6:ncol(data)],
  collapse = " + "
)
full_mod <- paste("~", full_mod)
```

```{r}
new_mod <- MASS::stepAIC(start_model,
  k = log(nrow(data)),
  trace = FALSE,
  scope = list(
    lower = ~1,
    upper = full_mod
  )
)
```

```{r}
dat <- summary(new_mod)$coefficients %>%
  signif(digits = 3)
```

```{r}
rnames <- rownames(dat) %>%
  stringr::str_replace_all("_", " ") %>%
  stringr::str_wrap(width = 20) %>%
  stringr::str_replace_all("\n", "<br/>")
```

```{r}
dat <- cbind(rnames, dat)
```

```{r}
knitr::kable(dat,
  row.names = FALSE,
  format.args = list(
    scientific = FALSE,
    drop0trailing = TRUE
  )
)
```

```{r}
all_coefs <- colnames(data)[6:ncol(data)]
mod_coefs <- rownames(summary(new_mod)$coefficients)[-1]

if (length(all_coefs) == length(mod_coefs)) {
  dropped_coefs <- "none"
} else {
  dropped_coefs <- all_coefs[(all_coefs %in% mod_coefs) == FALSE]

  if (length(dropped_coefs) > 1) {
    dropped_coefs <- paste(collapse = ",")
    # print(dropped_coefs)
  }
}
```

Dropped coefficients: `r dropped_coefs`


```{r, {{label}}-fig}
data$Predicted <- predict(new_mod, newdata = data) %>% exp()

fig <- ggplot2::ggplot(
  data,
  ggplot2::aes(
    x = Time,
    y = Value
  )
) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::geom_line(ggplot2::aes(y = Predicted),
    lty = 2,
    color = "red"
  ) +
  ggplot2::geom_point(ggplot2::aes(y = Predicted),
    color = "red"
  ) +
  ggplot2::ylab("Abundance") +
  ggplot2::xlab("Year") +
  ggplot2::theme_bw() +
  ggplot2::scale_y_continuous(
    labels = scales::comma,
    limits = c(0, NA)
  )

print(fig)
```

