--- 
title: "ESP Methods"
author: "Abigail Tyrell"
date: "`r format(Sys.time(), '%d %b %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: rtabandera/esp_data_aggregation
---

# Methods

## General methods
Northeast stocks were identified from NOAA/EDAB ECSA [seasonal species strata](https://github.com/NOAA-EDAB/ECSA/blob/master/data/seasonal_stock_strata.csv).

Data sources for each analysis are identified in the Results.

All continuous temporal data were plotted against time. If there were 30 or more years of data, a geom_gls regression line was fit (yellow = significant increase; purple = significant decrease; no line = no significant trend). If there were fewer than 30 years of data, no regression was fit.

## `assessmentdata` methods
Stock assessment and data quality information were compiled into a summary table.

B/Bmsy was classified as "DANGER" if it was below 1 and "GOOD" if it was above 1.

F/Fmsy was classified as "DANGER" if it was above 1 and "GOOD" if it was below 1.

## `survdat` methods
`survdat` data with zero abundance were not included in this analysis. Abundance and biomass were summed for each year and season. All other metrics were averaged for each year and season. The tables show summary statistics for the entire time series and for the most recent 5 years in the time series. 
