# Risk assessment

```{r, risk_functions, include = FALSE}
# none
```

```{r, risk_data, include = FALSE}
risk_data <- params$risk_data
risk_data <- risk_data[risk_data$Species == species, ]
```

A preliminary risk analysis was conducted by ranking all species according to their indicator values. A high rank number and a normalized rank near 1 indicates that the species is at risk or of importance based on the measured indicator values. When a species was missing an indicator, it was assigned a normalized rank of 0.5.

```{r, risk}
data <- risk_data %>% dplyr::mutate(Rank = paste(rank, "out of", n_stocks_per_indicator),
                       Value2 = Value %>% 
                         format(big.mark = ",", scientific = FALSE, digits = 2),
                       Normalized_rank = norm_rank %>% round(digits = 2)) %>%
  dplyr::select(Region, category, Indicator, Year, Value2, Rank, Normalized_rank) %>%
  dplyr::rename("Value" = "Value2") %>%
  character_to_factor()

DT::datatable(data, 
          rownames = FALSE,
          colnames = c("Region", "Category", "Indicator", "Year", "Value",
                       "Rank", "Normalized rank"),
          filter = list(position = 'top', 
                        clear = FALSE),
          extensions = 'Scroller',
          options = list(search = list(regex = TRUE),
                         deferRender = TRUE,
                         scrollY = 200,
                         scrollX = TRUE,
                         scroller = TRUE,
                         language = list(thousands = ",")))
```