# Management information

```{r, management_functions}
# none
```

```{r, management_data, cache = params$cache}
asmt_sum_data <- params$asmt_sum_data[params$asmt_sum_data$Species == species, ]

ad_rating_data <- params$asmt_sum_data %>% 
  dplyr::select(Species, Region, `Assessment Year`, `Last Data Year`,
                `Biological Input Data`, `Life History Data`, 
                `Composition Input Data`, `Ecosystem Linkage`, `FSSI Stock?`,
                `Review Result`) %>%
  dplyr::rename(`Biological Data Rating (2019)` = `Biological Input Data`,
                `Biological Data Rating (before 2019)` = `Life History Data`,
                `Size Data Rating` = `Composition Input Data`,
                `Ecosystem Linkage Data Rating` = `Ecosystem Linkage`,
                `FSSI status` = `FSSI Stock?`)
```

## Stock assessment and data quality information
Stock assessment and data quality information were pulled from ``r params$asmt_sum_source``.
```{r, quality}
data <- ad_rating_data %>%
  dplyr::filter(Species == species) %>%
  character_to_factor()

make_html_table(data, col_names = colnames(data))
```
