# Management information

```{r, management_functions, include = FALSE}
# none
```

```{r, management_data, include = FALSE}
# assessment data read in with pop data
#asmt_sum_data <- params$asmt_sum_data
#asmt_sum_data <- asmt_sum_data[asmt_sum_data$Species == species, ]

ad_rating_data <- asmt_sum_data %>% 
  dplyr::select(Species, Region, Assessment.Year, Last.Data.Year,
                Biological.Input.Data, Life.History.Data, 
                Composition.Input.Data, Ecosystem.Linkage, FSSI.Stock.,
                Review.Result) %>%
  dplyr::rename(`Assessment Year` = Assessment.Year,
                         `Last Data Year` = Last.Data.Year,
                         `Biological Data Rating (2019)` = Biological.Input.Data,
                         `Biological Data Rating (before 2019)` = Life.History.Data,
                         `Size Data Rating` = Composition.Input.Data,
                         `Ecosystem Linkage Data Rating` = Ecosystem.Linkage,
                         `FSSI status` = FSSI.Stock.,
                         `Review Result` = Review.Result)
```

## Stock assessment and data quality information
Stock assessment and data quality information were pulled from ``r params$asmt_sum_source``.
```{r, quality}
data <- ad_rating_data %>%
  character_to_factor()

DT::datatable(data, 
          rownames = FALSE,
          filter = list(position = 'top', 
                        clear = FALSE),
          extensions = 'Scroller',
          options = list(search = list(regex = TRUE),
                         deferRender = TRUE,
                         scrollY = 200,
                         scrollX = TRUE,
                         scroller = TRUE,
                         language = list(thousands = ",")))
```
