## Revenue 

```{r, revenue_functions, cache = params$cache}
source(here::here("R/full_report_functions", "get_com_money.R"))
```

```{r, revenue_raw_data}
com_data <- params$com_data[params$com_data$Species == species, ]
```

Commercial catch data were downloaded from [NOAA FOSS](https://foss.nmfs.noaa.gov/apexfoss/f?p=215:200:4615327020711::NO:::).

### Figure
```{r, revenue}
plot_com_money(com_data)
```

##### Risk {-}

See Methods for risk calculation details.
```{r}
indicators <- c("revenue")
```

```{r, child = here::here("bookdown", "_risk-child-doc.Rmd")}
```

### Data
```{r, revenue_data}
data <- com_data %>%
  dplyr::select(Year, State, Dollars_adj, Pounds) %>%
  dplyr::mutate(
    Dollars_adj = Dollars_adj %>%
      round(digits = 0) %>%
      format(big.mark = ","),
    State = State %>%
      stringr::str_to_title(),
    Pounds = Pounds %>%
      format(big.mark = ",")
  ) %>%
  dplyr::rename(
    "Revenue (2019 dollars)" = "Dollars_adj",
    "Commercial catch (lb)" = "Pounds"
  ) %>%
  character_to_factor()

make_html_table(data, col_names = colnames(data))
```
