---
title: "`r params$species_ID`"
author: "Abigail Tyrell"
date: "`r format(Sys.time(), '%d %b %Y')`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    split_by: section
documentclass: book
github-repo: NOAA-EDAB/esp_data_aggregation

language:
  ui:
    chapter_name: "Section "

params: 
  species_ID: "Acadian redfish" # common name of species
  
  latlong_data: data # strata
  shape: shape # shapefile
  
  asmt_sum_data: data # bbmsy, ffmsy, assessment ratings
  asmt_sum_source: "assessmentdata::stockAssessmentSummary"

  diet_data: data # allfh diet data
  
  survey_data: data # survey data
  survey_source: "survdat"
  
  ricky_survey_data: data # ricky survey data

  rec_data: data # recreational catch (MRIP)
  
  asmt_data: data # assessmentdata:stockAssessmentData, for recruitment and catch
  asmt_source: "assessmentdata::stockAssessmentData"
  
  cond_data: data # Laurel's condition data
  
  risk_data: data # relative risk rankings
  
  com_data: data # commercial catch
  
  swept_data: data # swept area estimates
  
  risk_year_hist_data: data # historical risk by year
  
  risk_year_value_data: data # value risk by year
  
  risk_species_data: data # species risk
  
  cache: FALSE
  
  path: "" # figure path
---

# `r params$species` {-}

```{r, setup, include = FALSE}
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      # record the current time before each chunk
      now <<- Sys.time()
    } else {
      # calculate the time difference after a chunk
      res <- difftime(Sys.time(), now) %>% round(digits = 2)
      # return a character string to show the time
      paste("Time for this code chunk to run:", res)
    }
  }
}))

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE, 
                      warning = FALSE, 
                      #time_it = TRUE,
                      fig.width = 8, 
                      fig.align = 'center',
                      fig.cap = params$species,
                      fig.path = params$path
                     # cache.path = here::here("bookdown/cache/", "")
                      )
```

```{r, setup2, cache = params$cache}
library(ggplot2)

`%>%` <- dplyr::`%>%`
```

```{r, universal_functions, cache = params$cache}
source(here::here("R", "character_to_factor.R"))
source(here::here("R/full_report_functions", "make_html_table.R"))

source(here::here("R/full_report_functions/risk_functions", "plot_risk_by_year.R"))
source(here::here("R/full_report_functions/risk_functions", "plot_risk_within_species.R"))
source(here::here("R/full_report_functions/risk_functions", "add_missing_na.R"))

```

```{r, species_data}
# data used in multiple chapters
species <- params$species_ID

risk_data <- params$risk_data[params$risk_data$Species == species, ] 
risk_data <- risk_data %>% missing_na()

risk_year_hist_data <- params$risk_year_hist_data[params$risk_year_hist_data$Species == species, ]
risk_year_hist_data <- risk_year_hist_data %>% missing_na()

risk_year_value_data <- params$risk_year_value_data[params$risk_year_value_data$Species == species, ] 
risk_year_value_data <- risk_year_value_data %>% missing_na()

risk_species_data <- params$risk_species_data[params$risk_species_data$Species == species, ] 
risk_species_data <- risk_species_data %>% missing_na()
```

This is a preliminary report of previously collected data. This report is pulling information on all Northeast `r species` stocks.
