## Catch, landings, and discards data

### Stock assessment catch
```{r, catch_data}
if (nrow(asmt_data) > 0) {
  data <- asmt_data %>%
    dplyr::filter(
      Metric == "Catch",
      Region != "Eastern Georges Bank"
    ) %>% # double counted
    dplyr::select(-Species, -Metric) %>%
    dplyr::mutate(options = paste(AssessmentYear, Description, Units, sep = " - ")) %>%
    #  dplyr::arrange(AssessmentYear) %>%
    dplyr::group_by(Year, options) %>%
    dplyr::summarise(Value = sum(Value)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(Value = Value %>%
      round(digits = 0) %>%
      format(big.mark = ",")) %>%
    tidyr::pivot_wider(
      names_from = options,
      values_from = Value
    ) %>%
    NEesp::character_to_factor()
} else {
  data <- asmt_data
}

NEesp::make_html_table(data,
  type = params$file
)
```

### Recreational landings
```{r, rec_data}
if (nrow(rec_data) > 0) {
  data <- rec_data %>%
    NEesp::rec_data_prep(state = TRUE) %>%
    dplyr::filter(name == "landings") %>%
    dplyr::mutate(
      State = st_f %>%
        stringr::str_to_sentence(),
      Method = mode_fx_f %>%
        stringr::str_to_sentence()
    ) %>%
    dplyr::select(year, State, Region, Method, value) %>%
    NEesp::character_to_factor()
} else {
  data <- rec_data
}

NEesp::make_html_table(data,
  type = params$file,
  col_names = c("Year", "State", "Region", "Method", "Landings (lb)")
)
```

### Commercial landings
```{r, com_data}
data <- com_data %>%
  dplyr::select(Year, State, Dollars_adj, Pounds) %>%
  dplyr::mutate(
    Dollars_adj = Dollars_adj %>%
      round(digits = 0) %>%
      format(big.mark = ","),
    State = State %>%
      stringr::str_to_title(),
    Pounds = Pounds %>%
      format(big.mark = ",")
  ) %>%
  dplyr::rename(
    "Revenue (2019 dollars)" = "Dollars_adj",
    "Commercial landings (lb)" = "Pounds"
  ) %>%
  NEesp::character_to_factor()


NEesp::make_html_table(data,
  type = params$file
)
```

### Commercial vs recreational landings
```{r, comvrec_data}
data <- NEesp::prop_catch_data(rec = rec_data, com = com_data) %>%
  NEesp::character_to_factor()

NEesp::make_html_table(data,
  type = params$file,
  col_names = c(
    "Year", "Recreational landings",
    "Commercial landings", "Total landings",
    "Proportion recreational",
    "Proportion commercial"
  )
)
```

### Commercial and recreational landings, and stock assessment catch
```{r, all_catch}
stock <- asmt_data %>%
  dplyr::filter(
    Metric == "Catch",
    Region != "Eastern Georges Bank"
  ) %>% # double counted
  dplyr::mutate(options = paste(AssessmentYear, Description, Units, sep = " - ")) %>%
  dplyr::group_by(Year, options) %>%
  dplyr::summarise(Value = sum(Value)) %>%
  dplyr::ungroup() %>%
  tidyr::pivot_wider(
    names_from = options,
    values_from = Value
  )

recr <- rec_data %>%
  dplyr::mutate(catch = lbs_ab1 %>%
    as.numeric()) %>%
  dplyr::group_by(year) %>%
  dplyr::rename(Year = year) %>%
  dplyr::summarise(`Recreational catch (mt)` = sum(catch) / 2204.6)

comm <- com_data %>%
  dplyr::group_by(Year) %>%
  dplyr::summarise(`Commercial catch (mt)` = sum(Pounds) / 2204.6)

if (nrow(stock) > 0) {
  all_catch <- stock
}

if (nrow(recr) > 0) {
  if (exists("all_catch")) {
    all_catch <- dplyr::full_join(all_catch, recr, by = "Year")
  } else {
    all_catch <- recr
  }
}

if (nrow(comm) > 0) {
  if (exists("all_catch")) {
    all_catch <- dplyr::full_join(all_catch, comm, by = "Year")
  } else {
    all_catch <- comm
  }
}

if (exists("all_catch")) {
  if (ncol(all_catch > 2)) {
    all_catch <- all_catch %>%
      dplyr::arrange(Year) %>%
      round(digits = 0) %>%
      # format(big.mark = ",") %>% # messing up formatting
      as.data.frame()

    all_catch <- all_catch %>% dplyr::select("Year", sort(colnames(all_catch)[-1]))
  }
}

# make sure there is data on at least 2 types of catch
test <- c(nrow(stock), nrow(recr), nrow(comm))
sum_test <- sum(test == 0)

if (sum_test >= 2) {
  print("NO DATA")
} else {
  NEesp::make_html_table(all_catch,
    type = params$file
  )
}
```
