---
title: "Black sea bass indicator analysis"
author: "Abigail Tyrell"
date: "`r format(Sys.time(), '%d %b %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.height = 8
)

`%>%` <- magrittr::`%>%`

plot_corr_only <- function(data, title = "") {
  if (nrow(data) > 0) {
    my_colors <- c("black", "#B2292E", "gray")
    names(my_colors) <- c("FALSE", "TRUE", "NA")

    fig <- ggplot2::ggplot(data, ggplot2::aes(
      x = Val,
      y = Value
    )) +
      ggplot2::geom_path(ggplot2::aes(color = Time)) +
      ggplot2::geom_point(ggplot2::aes(color = Time)) +
      ggplot2::scale_color_gradient(
        low = "#7F7FFF",
        high = "#575195", breaks = seq(1950, 2020,
          by = 10
        ),
        name = "Year"
      ) +
      ggnewscale::new_scale_color() +
      ggplot2::stat_smooth(ggplot2::aes(color = sig),
        method = "lm"
      ) +
      ggplot2::scale_color_manual(
        values = my_colors,
        name = "Statistically significant\n(p < 0.05)"
      ) +
      ggplot2::scale_y_continuous(labels = scales::comma) +
      ggplot2::scale_x_continuous(labels = scales::comma) +
      ggplot2::theme_bw() +
      ggplot2::labs(title = "Correlation between black sea bass and indicator") +
      ggplot2::ylab(unique(data$Metric)) +
      ggplot2::xlab(unique(data$Var))
    
    # test if bsb is sig over time - overwrite sig
    model <- lm(Value ~ Time, data = data)
    pval <- summary(model)$coefficients[2, 4]
    data$sig <- (pval < 0.05)
    
    bsb_fig <- ggplot2::ggplot(data, ggplot2::aes(
      x = Time,
      y = Value
    )) +
      ggplot2::geom_path(ggplot2::aes(color = Time)) +
      ggplot2::geom_point(ggplot2::aes(color = Time)) +
      ggplot2::scale_color_gradient(
        low = "#7F7FFF",
        high = "#575195", 
        breaks = seq(1950, 2020,
          by = 10
        ),
        name = "Year"
      ) +
      ggnewscale::new_scale_color() +
      ggplot2::stat_smooth(ggplot2::aes(color = sig),
        method = "lm"
      ) +
      ggplot2::scale_color_manual(
        values = my_colors,
        name = "Statistically significant\n(p < 0.05)"
      ) +
      ggplot2::scale_y_continuous(labels = scales::comma) +
      ggplot2::theme_bw() +
      ggplot2::labs(title = "Black sea bass over time") +
      ggplot2::xlab("Year") +
      ggplot2::ylab(unique(data$Metric))
    
    # test if indicator is sig over time - overwrite sig
    model <- lm(Val ~ Time, data = data)
    pval <- summary(model)$coefficients[2, 4]
    data$sig <- (pval < 0.05)
    
    ind_fig <- ggplot2::ggplot(data, ggplot2::aes(
      x = Time,
      y = Val
    )) +
      ggplot2::geom_path(ggplot2::aes(color = Time)) +
      ggplot2::geom_point(ggplot2::aes(color = Time)) +
      ggplot2::scale_color_gradient(
        low = "#7F7FFF",
        high = "#575195", breaks = seq(1950, 2020,
          by = 10
        ),
        name = "Year"
      ) +
      ggnewscale::new_scale_color() +
      ggplot2::stat_smooth(ggplot2::aes(color = sig),
        method = "lm"
      ) +
      ggplot2::scale_color_manual(
        values = my_colors,
        name = "Statistically significant\n(p < 0.05)"
      ) +
      ggplot2::scale_y_continuous(labels = scales::comma) +
      ggplot2::theme_bw() +
      ggplot2::labs(title = "Indicator over time") +
      ggplot2::xlab("Year") +
      ggplot2::ylab(unique(data$Var))
    
    big_fig <- ggpubr::ggarrange(ggpubr::ggarrange(bsb_fig, ind_fig, 
                                                   ncol = 2,
                                                   legend = "none",
                                                   labels = c("A", "B")), 
                                 fig,
                                 common.legend = TRUE,
                                 legend = "top",
                                 nrow = 2,
                                 labels = c(NA, "C")) +
       ggplot2::theme(plot.background = ggplot2::element_rect(color = "black", size = 1),
                      plot.margin = ggplot2::unit(c(0.1,0.1,0.1,0.1), "cm"))
    
    ggpubr::annotate_figure(big_fig, top = title)
    
    return(big_fig)
  }
  else {
    print("No data under conditions selected")
  }
}

prep_data <- function(data) {
  data <- data %>%
    read.csv() %>%
    dplyr::filter(
      Metric == "Recruitment",
      stringr::str_detect(Var, "north", negate = TRUE),
      stringr::str_detect(Var, "south", negate = TRUE)
    ) %>%
    dplyr::mutate(Var = Var %>%
      stringr::str_replace_all("\n", " ") %>%
      stringr::str_wrap(40))

  return(data)
}
```

## Recruitment 

### Winter SST anomaly
```{r}
here::here(
  "black-sea-bass", "Black sea bass_regression_report_0lag", "data",
  "Black_sea_bass_Mid_MAB_0_lag_FALSE_remove_recent_sst-anom-stock.csv"
) %>%
  prep_data() %>%
    dplyr::filter(stringr::str_detect(Var, "winter")) %>%
  plot_corr_only()
```

### Fall SST anomaly (prior year)
```{r}
here::here(
  "black-sea-bass", "Black sea bass_regression_report_1lag", "data",
  "Black_sea_bass_Mid_MAB_1_lag_FALSE_remove_recent_sst-anom-stock.csv"
) %>%
    prep_data() %>%
  dplyr::filter(stringr::str_detect(Var, "fall")) %>%
  plot_corr_only()
```

### Winter primary production
```{r}
here::here(
  "black-sea-bass", "Black sea bass_regression_report_0lag", "data",
  "Black_sea_bass_Mid_MAB_0_lag_FALSE_remove_recent_pp-stock.csv"
) %>%
    prep_data() %>%
  dplyr::filter(stringr::str_detect(Var, "winter")) %>%
  plot_corr_only()
```

### Fall primary production (prior year)
```{r}
here::here(
  "black-sea-bass", "Black sea bass_regression_report_1lag", "data",
  "Black_sea_bass_Mid_MAB_1_lag_FALSE_remove_recent_pp-stock.csv"
) %>%
    prep_data() %>%
  dplyr::filter(stringr::str_detect(Var, "fall")) %>%
  plot_corr_only()
```

### Cold pool index (prior year)
```{r}
data <- here::here(
  "black-sea-bass", "Black sea bass_regression_report_1lag", "data",
  "Black_sea_bass_Mid_MAB_1_lag_FALSE_remove_recent_cold-pool.csv"
) %>%
  prep_data() 

for(i in unique(data$Var)){
  this_data <- data %>%
    dplyr::filter(Var == i)
  plt <- plot_corr_only(this_data, title = i)
  print(plt)
  cat("\n\n")
}
```

### Predator abundance


## Ecosystem

### Sea surface temperature

### Marine heatwaves


## Management

### Northern and southern bounds

### Center of gravity

### Total catch

### CPUE

### Catch vs TAC

