---
title: "Untitled"
author: "Abigail Tyrell"
date: "4/23/2021"
output: html_document
params:
  lag: 0 # lag for correlations
  remove_recent: FALSE
  cache: FALSE
  stock: 
  epu: MAB # epu options: GB, GOM, MAB, SS, All, OTHER, MA, NE, all 
  region: "" # the stock region
  path: "" # figure path
  save: TRUE
  out: "html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

`%>%` <- magrittr::`%>%`
```

# Create northern and southern bound data sets

## Northern bound
```{r, northern-bound}
test <- NEesp::survey %>%
  dplyr::filter(Species == "Black sea bass",
                ABUNDANCE > 0) %>% # why are there entries with 0 abundance but >0 biomass??
  dplyr::select(YEAR, LAT) %>% 
  dplyr::group_by(YEAR) %>%
  dplyr::mutate(max_lat = max(LAT, na.rm = TRUE)) %>%
  dplyr::select(-LAT) %>%
  dplyr::rename(Time = YEAR) %>%
  dplyr::distinct()
NEesp::render_indicator(test, lab = names[1])
```

## Southern bound
```{r, southern-bound}
test <- NEesp::survey %>%
  dplyr::filter(Species == "Black sea bass",
                ABUNDANCE > 0) %>% # why are there entries with 0 abundance but >0 biomass??
  dplyr::select(YEAR, LAT)  %>% 
  dplyr::group_by(YEAR) %>%
  dplyr::mutate(min_lat = min(LAT, na.rm = TRUE)) %>%
  dplyr::select(-LAT) %>%
  dplyr::rename(Time = YEAR) %>%
  dplyr::distinct()
NEesp::render_indicator(test, lab = names[1])
```
