on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,4"

name: Create new cache

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
        
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      
      - name: Check cached R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: cache-09142021-AT
          
      - name: Install more packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("devtools", "stringi", "car"))
          devtools::install_github("NOAA-EDAB/NEesp", ref = "v0.1.1", dependencies = TRUE)'
