on:
  workflow_dispatch:

name: Regression Reports (development)

jobs: 
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - name: Set up environment
        uses: NOAA-EDAB/esp_data_aggregation/.github@abby
                 
      - name: Render reports
        run: |
          Rscript -e 'remove.packages("NEesp")
          remotes::install_github("NOAA-EDAB/NEesp", ref = "dev", upgrade = "never") # use dev version
          install.packages("ggnewscale")
          NEesp::render_all_reg(species = NEesp::regression_species_regions[1:10,])'
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch
          
  build2:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - name: Set up environment
        uses: NOAA-EDAB/esp_data_aggregation/.github@abby
                 
      - name: Render reports
        run: |
          Rscript -e 'remove.packages("NEesp")
          remotes::install_github("NOAA-EDAB/NEesp", ref = "dev", upgrade = "never") # use dev version
          install.packages("ggnewscale")
          NEesp::render_all_reg(species = NEesp::regression_species_regions[11:20,])'
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch
          
  build3:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - name: Set up environment
        uses: NOAA-EDAB/esp_data_aggregation/.github@abby
                 
      - name: Render reports
        run: |
          Rscript -e 'remove.packages("NEesp")
          remotes::install_github("NOAA-EDAB/NEesp", ref = "dev", upgrade = "never") # use dev version
          install.packages("ggnewscale")
          NEesp::render_all_reg(species = NEesp::regression_species_regions[21:30,])'
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch

  build4:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - name: Set up environment
        uses: NOAA-EDAB/esp_data_aggregation/.github@abby
                 
      - name: Render reports
        run: |
          Rscript -e 'remove.packages("NEesp")
          remotes::install_github("NOAA-EDAB/NEesp", ref = "dev", upgrade = "never") # use dev version
          install.packages("ggnewscale")
          NEesp::render_all_reg(species = NEesp::regression_species_regions[31:40,])'
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch
          
   build5:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - name: Set up environment
        uses: NOAA-EDAB/esp_data_aggregation/.github@abby
                 
      - name: Render reports
        run: |
          Rscript -e 'remove.packages("NEesp")
          remotes::install_github("NOAA-EDAB/NEesp", ref = "dev", upgrade = "never") # use dev version
          install.packages("ggnewscale")
          NEesp::render_all_reg(species = NEesp::regression_species_regions[41:50,])'
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch   
          
  build6:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - name: Set up environment
        uses: NOAA-EDAB/esp_data_aggregation/.github@abby
                 
      - name: Render reports
        run: |
          Rscript -e 'remove.packages("NEesp")
          remotes::install_github("NOAA-EDAB/NEesp", ref = "dev", upgrade = "never") # use dev version
          install.packages("ggnewscale")
          NEesp::render_all_reg(species = NEesp::regression_species_regions[51:61,])'
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch          
          
