on:
  workflow_dispatch:

name: Regression Reports (development)

jobs: 
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Install Pandoc
        run: brew install pandoc
        shell: bash

      - name: Install command line packages
        run: |        
          sudo apt update
          sudo apt-get install  libgdal-dev libcurl4-gnutls-dev libgit2-dev libudunits2-dev
        shell: bash
        
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with: 
          r-version: '4.0.3' # problem with using 4.0.4        
      
      - name: Cache R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: bigger-cache-more-packages-05192021-AT
                 
      - name: Render reports
        run: |
          Rscript -e 'remove.packages("NEesp")
          remotes::install_github("NOAA-EDAB/NEesp", ref = "dev", upgrade = "never") # use dev version
          remove.packages("ecodata")
          remotes::install_github("NOAA-EDAB/ecodata", upgrade = "never")
          install.packages("ggnewscale")
          source(here::here("R-scripts", "render regression dev report with errors.R"))'
          
      - name: Cache more R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: test-cache-07022021-AT
          
      - name: Change to 8-bit
        run: |
          sudo apt-get install -y pngquant
          cd Regressions
          du -s
          pngquant --quality=0-90 --force --ext .png */*/*/*.png
          du -s
        shell: bash 
        
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GH_PAT }}
          ignorePaths: 'Reports/**, black-sea-bass/**, R-scripts/**'
          compressOnly: true
          
      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch
