on:
  workflow_dispatch:

name: Regression Reports (development)

jobs: 
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Install Pandoc
        run: brew install pandoc
        shell: bash

      - name: Install command line packages
        run: |        
          sudo apt update
          sudo apt-get install  libgdal-dev libcurl4-gnutls-dev libgit2-dev libudunits2-dev
        shell: bash
        
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with: 
          r-version: '4.0.3' # problem with using 4.0.4        
      
      - name: Cache R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: bigger-cache-more-packages-05192021-AT
                 
      - name: Render reports 1-10
        run: |
          Rscript -e 'remove.packages("NEesp")
          remotes::install_github("NOAA-EDAB/NEesp", ref = "dev", upgrade = "never") # use dev version
          install.packages("ggnewscale")
          NEesp::render_all_reg(species = NEesp::regression_species_regions[1:10,])'
          
      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch

      - name: Render reports 11-15
        run: |
          Rscript -e 'unlink(here::here("Regressions", recursive = TRUE))
          NEesp::render_all_reg(species = NEesp::regression_species_regions[11:15,])'

      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
        
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch

      - name: Render reports 16-18
        run: |
          Rscript -e 'unlink(here::here("Regressions"), recursive = TRUE)
          NEesp::render_all_reg(species = NEesp::regression_species_regions[16:18,])'

      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
        
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch
          
      - name: Render reports 19-20
        run: |
          Rscript -e 'unlink(here::here("Regressions"), recursive = TRUE)
          NEesp::render_all_reg(species = NEesp::regression_species_regions[19:20,])'

      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
        
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch
          
      - name: Render reports 21-30
        run: |
          Rscript -e 'unlink(here::here("Regressions"), recursive = TRUE)
          NEesp::render_all_reg(species = NEesp::regression_species_regions[21:30,])'

      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
        
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch

      - name: Render reports 31-40
        run: |
          Rscript -e 'unlink(here::here("Regressions"), recursive = TRUE)
          NEesp::render_all_reg(species = NEesp::regression_species_regions[31:40,])'

      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
        
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch

      - name: Render reports 41-50
        run: |
          Rscript -e 'unlink(here::here("Regressions"), recursive = TRUE)
          NEesp::render_all_reg(species = NEesp::regression_species_regions[41:50,])'

      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
        
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch   

      - name: Render reports 51-61
        run: |
          Rscript -e 'unlink(here::here("Regressions"), recursive = TRUE)
          NEesp::render_all_reg(species = NEesp::regression_species_regions[51:61,])'

      - name: Check directory size
        run: |
          cd Regressions
          du -s
        shell: bash
        
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: NOAA-EDAB/ESP_docs
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: Regressions # The folder the action should deploy.
          target-folder: Regression_reports
          clean: false # Automatically remove deleted files from the deploy branch          
          