on:
  workflow_dispatch:

name: Test deploying on ESP_docs
jobs: 
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:          
      - name: Checkout esp_data_aggregation
        uses: actions/checkout@v2
        with:
          path: abby

      - name: Checkout ESP_docs
        uses: actions/checkout@v2
        with:
          repository: NOAA-EDAB/ESP_docs
          path: main
              
      - name: Make a folder
        run: mkdir "test-folder"
        shell: bash

      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          REPOSITORY_NAME: ESP_docs
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: test-folder # The folder the action should deploy.
          TARGET_FOLDER: Reports
          CLEAN: false # Automatically remove deleted files from the deploy branch
